### ISSUE TITLE
Add message saving function

### ISSUE THREAD

**Issue by VoidxRose** [AkaiiKitsune/discordLoggerBot#1]
Add a function that will add messages sent in servers the bot is in to the database

**Comment by Theocrat** [comment]
I've made one. Please check if it is working by testing the bot.

**Comment by Theocrat** [comment]
I have tested the `logMsg` implementation, and it is working perfectly so far.

Time to close this issue :)

**Comment by Theocrat** [comment]
Since the functionality has been implemented and merged into `Database_development`, I hereby, with the authority bestowed upon me by the decree of the all-mighty Database Gods, declare this issue closed. Good riddance. That was a nightmare merge.
